version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: prod_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Optional: Auto-run schema

  app:
    build: .  # Your Dockerfile from Restaurant App
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: prod_db
      DB_USER: postgres
      DB_PASS: password
    volumes:
      - .:/app  # For dev hot-reload

volumes:
  postgres_data: